import type { Metadata } from "next";
import { Manrope, Outfit } from "next/font/google";
import "./globals.css";
import ClientLoader from "@/components/global/Loader/ClientLoader";
import SmoothScrolling from "@/components/global/SmoothScrolling";
import { LoaderProvider } from "@/context/LoaderContext";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${outfit.variable} ${manrope.variable} antialiased`}>
        <LoaderProvider>
          <ClientLoader />
          <SmoothScrolling>{children}</SmoothScrolling>
        </LoaderProvider>
      </body>
    </html>
  );
}
